In [2]:
import numpy as np
import pandas as pd
import re
import nltk
import string

In [3]:
import pandas as pd

df = pd.read_json("hf://datasets/ru-dataset/tg-ru-engagement/channel_data_clean.json")

In [4]:
df.head(10)

,id,date,text,links,has_links,has_media,media_type,views,forwards,reply_to
0,42952,2026-07-21 18:42:01+00:00,Новая версия Telegram перегревает iPhone и зав...,[],False,True,photo,44198,277,NaN
1,42953,2026-07-21 18:58:01+00:00,В России хотят разрешить ставить на учёт машин...,[],False,False,NaN,42846,201,NaN
2,42954,2026-07-21 19:43:01+00:00,Суд обязал девушку выплатить 10 тысяч рублей м...,[],False,True,video,51331,606,NaN
3,42955,2026-07-21 20:28:01+00:00,"Франция стала первой страной Евросоюза, приняв...",[],False,False,NaN,48342,225,NaN
4,42956,2026-07-21 22:05:14+00:00,Завтракающие каждый день на 28% реже покупают ...,[],False,False,NaN,48507,481,NaN
5,42957,2026-07-22 04:09:49+00:00,Логистические центры Wildberries в Краснодаре ...,[],False,False,NaN,48382,357,NaN
6,42958,2026-07-22 05:05:17+00:00,"ЦБ, скорее всего, не станет менять ключевую ст...",[],False,False,NaN,46038,49,NaN
7,42959,2026-07-22 05:26:01+00:00,Мошенники начали разводить пользователей прини...,[],False,True,photo,48143,182,NaN
8,42962,2026-07-22 06:02:01+00:00,Россиян предупредили о новой схеме мошенничест...,[],False,False,NaN,41716,265,NaN
9,42963,2026-07-22 06:33:01+00:00,Заморозить цены на продукты предложили в Госду...,[],False,False,NaN,41195,147,NaN

In [5]:
##Нижний регистр.
df['text_lower']  = df['text'].str.lower()
df['text_lower'].head()

0    новая версия telegram перегревает iphone и зав...
1    в россии хотят разрешить ставить на учёт машин...
2    суд обязал девушку выплатить 10 тысяч рублей м...
3    франция стала первой страной евросоюза, приняв...
4    завтракающие каждый день на 28% реже покупают ...
Name: text_lower, dtype: str

In [6]:
#Удаление пунктуации    !!!!!!НЕ УДАЛЯЕТ!!!!!
df['text_lower'] = df['text_lower'].str.replace('[^\w\s]','')
df['text_lower'].head()

<>:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\psitn\AppData\Local\Temp\ipykernel_15768\137225609.py:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df['text_lower'] = df['text_lower'].str.replace('[^\w\s]','')

0    новая версия telegram перегревает iphone и зав...
1    в россии хотят разрешить ставить на учёт машин...
2    суд обязал девушку выплатить 10 тысяч рублей м...
3    франция стала первой страной евросоюза, приняв...
4    завтракающие каждый день на 28% реже покупают ...
Name: text_lower, dtype: str

In [7]:
#nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('russian'))

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между']

In [8]:
#Удаление стоп-слов
#Импорт стоп-слов из бибилиотеки nltk
from nltk.corpus import stopwords
STOPWORDS = set(stopwords.words('russian'))
# функция, удаляющая стопслова из текстов

def stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
# Применим функцию удаления стоп-слов
df["text_lower"] = df["text_lower"].apply(stopwords)
df["text_lower"].head()

0    новая версия telegram перегревает iphone завал...
1    россии хотят разрешить ставить учёт машины, ко...
2    суд обязал девушку выплатить 10 тысяч рублей м...
3    франция стала первой страной евросоюза, приняв...
4    завтракающие каждый день 28% реже покупают вещ...
Name: text_lower, dtype: str

In [9]:
#Удаление высокочастотных слов
from collections import Counter
cnt = Counter()
for text in df["text_lower"].values:
    for word in text.split():
        cnt[word] += 1
        
cnt.most_common(20)

[('—', 49086),
 ('@bezposhady', 34194),
 ('подписаться', 28977),
 ('топор', 28370),
 ('👉', 28264),
 ('+18.', 24860),
 ('это', 8848),
 ('россии', 6778),
 ('из-за', 5762),
 ('тысяч', 4641),
 ('рублей', 4175),
 ('рублей.', 3978),
 ('также', 3920),
 ('могут', 3621),
 ('которые', 3494),
 ('который', 3373),
 ('года', 3210),
 ('её', 3093),
 ('время', 3061),
 ('•', 2943)]

In [10]:
#удаление часто встречающиеся слов в корпусе при помощи tf-idf
# Удаление самых частотных слов
freq = set([w for (w, wc) in cnt.most_common(10)])
# функция удаления слов
def freqwords(text):
    return " ".join([word for word in str(text).split() if word not 
in freq])
# применение функции
df["text_lower"] = df["text_lower"].apply(freqwords)
df["text_lower"].head()

0    новая версия telegram перегревает iphone завал...
1    хотят разрешить ставить учёт машины, которые ч...
2    суд обязал девушку выплатить 10 рублей мужчине...
3    франция стала первой страной евросоюза, приняв...
4    завтракающие каждый день 28% реже покупают вещ...
Name: text_lower, dtype: str

In [11]:
#Удаление низкочастотных слов
freq = pd.Series(' '.join(df['text_lower']).split()).value_counts()[-10:] # 10 rare words
freq = list(freq.index)
df['text_lower'] = df['text_lower'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
df['text_lower'].head()

0    новая версия telegram перегревает iphone завал...
1    хотят разрешить ставить учёт машины, которые ч...
2    суд обязал девушку выплатить 10 рублей мужчине...
3    франция стала первой страной евросоюза, приняв...
4    завтракающие каждый день 28% реже покупают вещ...
Name: text_lower, dtype: str

In [12]:
# Удаление эмодзи
def emoji(string):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', string)
#passing the emoji function to 'text_rare'
df['text_lower'] = df['text_lower'].apply(emoji)

In [13]:
#Удаление цифр   !!!! ТОЖЕ НЕ УДАЛЯЕТ !!!!!
df['text_lower'] = df['text_lower'].re.sub(r'_u\d_v\d', '_u%d_v%d', inputtext) 
df['text_lower'].head()

AttributeError: 'Series' object has no attribute 're'

In [13]:
print(repr(df['text_lower'][3]))

'франция стала первой страной евросоюза, принявшей закон запрете соцсетей детей 15 лет. документ вступает силу 1 сентября. входа соцсети пользователям нужно подтверждать возраст, платформы будут обязаны блокировать доступ несовершеннолетним. исключение сделано видео youtube переписок мессенджерах.'

In [14]:
#Удаление URL
# Function for url's
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [15]:
#Удаление HTML-тегов
from bs4 import BeautifulSoup
#Function for removing html
def html(text):
    return BeautifulSoup(text, "lxml").text

# Passing the function to 'text_rare'
df['text_lower'] = df['text_lower'].apply(html)

C:\Users\psitn\AppData\Local\Temp\ipykernel_15348\1129559862.py:5: MarkupResemblesLocatorWarning: The input passed in on this line looks more like a URL than HTML or XML.

If you meant to use Beautiful Soup to parse the web page found at a certain URL, then something has gone wrong. You should use an Python package like 'requests' to fetch the content behind the URL. Once you have the content as a string, you can feed that string into Beautiful Soup.

However, if you want to parse some data that happens to look like a URL, then nothing has gone wrong: you are using Beautiful Soup correctly, and this warning is spurious and can be filtered. To make this warning go away, run this code before calling the BeautifulSoup constructor:

    from bs4 import MarkupResemblesLocatorWarning
    import warnings

    warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

  return BeautifulSoup(text, "lxml").text

In [16]:
#Токенизация
def tokenization(text):
    text = re.split('\W+', text)
    return text
# Passing the function to 'text_rare' and store into'text_token'
df['ready'] = df['text_lower'].apply(lambda x: tokenization(x.lower()))
df[['ready']].head()

<>:3: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
<>:3: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
C:\Users\psitn\AppData\Local\Temp\ipykernel_15348\3393277205.py:3: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
  text = re.split('\W+', text)

                                               ready
0  [новая, версия, telegram, перегревает, iphone,...
1  [хотят, разрешить, ставить, учёт, машины, кото...
2  [суд, обязал, девушку, выплатить, 10, рублей, ...
3  [франция, стала, первой, страной, евросоюза, п...
4  [завтракающие, каждый, день, 28, реже, покупаю...

In [17]:
#Можно выполнить при помощи NLTK. Заодно проведем лемматизацию
from pymorphy3 import MorphAnalyzer
from nltk import sent_tokenize, word_tokenize, regexp_tokenize

def tokenize_lemmas(sent, pat=r"(?u)\b\w\w+\b", morph=MorphAnalyzer()):
    return [morph.parse(tok)[0].normal_form 
            for tok in regexp_tokenize(sent, pat)]
df["text_lower"] = df["text_lower"].map(lambda x: " ".join(tokenize_lemmas(x)))
df[['text_lower']].head()

                                          text_lower
0  новый версия telegram перегревать iphone завал...
1  хотеть разрешить ставить учёт машина который ч...
2  суд обязать девушка выплатить 10 рубль мужчина...
3  франция стать первый страна евросоюз принять з...
4  завтракать каждый день 28 редкий покупать вещь...

In [18]:
import torch
from transformers import AutoModelForSequenceClassification
from transformers import BertTokenizerFast

tokenizer = BertTokenizerFast.from_pretrained('blanchefort/rubert-base-cased-sentiment')
model = AutoModelForSequenceClassification.from_pretrained('blanchefort/rubert-base-cased-sentiment', return_dict=True)


def predict(text):
    inputs = tokenizer(text, max_length=512, padding=True, truncation=True, return_tensors='pt')
    outputs = model(**inputs)
    predicted = torch.nn.functional.softmax(outputs.logits, dim=1)
    predicted = torch.argmax(predicted, dim=1).numpy()
    return predicted

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [19]:
import sqlite3
connection = sqlite3.connect('C:/Users/psitn/OneDrive/Desktop/python/preproc/etym.db')

In [20]:
cursor = connection.cursor()

In [21]:
cursor.execute('SELECT * FROM links')
users = cursor.fetchall()

In [22]:
for user in users:
    print(user)

# Закрываем соединение
connection.close()

(623, 523, 1, 1, 'a', 2)
(624, 523, 1, 2, 'i', 1)
(625, 524, 1, 1, 'а', 1)
(626, 525, 0, 1, 'не', 0)
(627, 526, 0, 1, 'ажур', 1)
(628, 526, 0, 2, 'бат', 1)
(629, 527, 0, 1, 'базь', 0)
(630, 529, 0, 1, 'бе', 2)
(631, 530, 1, 1, 'а́збука', 0)
(632, 530, 1, 2, 'алфа́віт', 0)
(633, 531, 0, 1, 'абажу́р', 0)
(634, 531, 0, 2, 'сади́ти', 0)
(635, 531, 1, 1, 'о́бца́с', 0)
(636, 533, 0, 1, 'бир', 1)
(637, 534, 0, 1, 'аби́', 0)
(638, 534, 0, 2, 'що', 0)
(639, 535, 0, 1, 'а', 1)
(640, 535, 0, 2, 'бо', 0)
(641, 535, 1, 1, 'а́льбо́', 0)
(642, 536, 0, 1, 'мовня́', 0)
(643, 538, 0, 1, 'абажу́р', 0)
(644, 538, 0, 2, 'рони́ти', 0)
(645, 539, 0, 1, 'абажу́р', 0)
(646, 540, 0, 1, 'пекти́', 0)
(647, 540, 0, 2, 'при', 0)
(648, 541, 0, 1, 'бруку', 0)
(649, 542, 0, 1, 'абажу́р', 0)
(650, 542, 0, 2, 'ла́ва', 0)
(651, 542, 0, 3, 'свій', 0)
(652, 542, 0, 4, 'себе́', 0)
(653, 543, 0, 1, 'абажу́р', 0)
(654, 544, 0, 1, 'абажу́р', 0)
(655, 546, 0, 1, 'а́бза́ц', 0)
(656, 548, 0, 1, 'а', 2)
(657, 549, 0, 1, 'абажур', 0)
(658, 549, 0, 2, 'анти-', 0)
(659, 549, 0, 3, 'варта', 0)
(660, 549, 0, 4, 'гвардія', 0)
(661, 550, 0, 1, 'авангард', 0)
(662, 553, 0, 1, 'обр', 0)
(663, 556, 1, 1, 'алажа́', 0)
(664, 557, 1, 1, 'а́втор', 0)
(665, 558, 0, 1, 'ду́нька', 0)
(666, 562, 0, 1, 'Август', 0)
(667, 563, 0, 1, 'a', 1)
(668, 563, 0, 2, 'ce', 0)
(669, 563, 1, 1, 'гав', 2)
(670, 567, 1, 1, 'абрю́', 0)
(671, 569, 0, 1, 'авто-', 0)
(672, 570, 0, 1, 'автомобі́ль', 0)
(673, 570, 0, 2, 'авто-', 0)
(674, 572, 0, 1, 'авто-', 0)
(675, 572, 0, 2, 'о́мнібус', 0)
(676, 573, 0, 1, 'авто-', 0)
(677, 573, 0, 2, 'ген', 1)
(678, 574, 0, 1, 'авто-', 0)
(679, 574, 0, 2, 'графа́', 0)
(680, 575, 0, 1, 'автомобі́ль', 0)
(681, 575, 0, 2, 'олі́я', 0)
(682, 576, 0, 1, 'авто-', 0)
(683, 576, 0, 2, 'мни́мий', 0)
(684, 576, 0, 3, 'па́м’ять', 0)
(685, 577, 0, 1, 'авто-', 0)
(686, 577, 0, 2, 'мобі́льний', 0)
(687, 578, 0, 1, 'автоно́мія', 0)
(688, 579, 0, 1, 'авто-', 0)
(689, 580, 0, 1, 'А́вгуст', 0)
(690, 581, 0, 1, 'а́втор', 0)
(691, 583, 0, 1, 'огу́лом', 0)
(692, 583, 0, 2, 'аге́л', 1)
(693, 585, 0, 1, 'а́ва', 1)
(694, 587, 1, 1, 'га', 1)
(695, 588, 0, 1, 'ага', 1)
(696, 592, 0, 1, 'Ага́фія', 0)
(697, 593, 0, 1, 'Ага́фія', 0)
(698, 593, 0, 2, 'Ни́кон', 0)
(699, 594, 1, 1, 'ау́л', 0)
(700, 595, 0, 1, 'а́нгел', 0)
(701, 596, 1, 1, 'аго́нія', 0)
(702, 598, 0, 1, 'а', 1)
(703, 598, 0, 2, 'гі', 0)
(704, 598, 1, 1, 'iгі́', 0)
(705, 599, 0, 1, 'а́ге́нт', 0)
(706, 600, 0, 1, 'вид', 0)
(707, 601, 0, 1, 'А́гнія', 0)
(708, 602, 0, 1, 'ягня́', 0)
(709, 603, 1, 1, 'Агне́са', 0)
(710, 604, 0, 1, 'гов', 0)
(711, 605, 1, 1, 'а́ге́нт', 0)
(712, 606, 0, 1, 'а', 1)
(713, 606, 0, 2, 'ось', 0)
(714, 607, 0, 1, 'а́ге́нт', 0)
(715, 607, 0, 2, 'аго́нія', 0)
(716, 608, 0, 1, 'авантю́ра', 0)
(717, 608, 0, 2, 'го́рстка', 0)
(718, 608, 0, 3, 'горта́ти', 0)
(719, 609, 0, 1, 'авантю́ра', 0)
(720, 611, 0, 1, 'агра́рний', 0)
(721, 612, 0, 1, 'агра́рний', 0)
(722, 612, 0, 2, 'автоно́мія', 0)
(723, 614, 0, 1, 'а', 1)
(724, 614, 0, 2, 'гуш', 0)
(725, 615, 1, 1, 'аго́в', 0)
(726, 615, 1, 2, 'ау́', 0)
(727, 616, 0, 1, 'аги́', 0)
(728, 616, 0, 2, 'агу́', 1)
(729, 621, 1, 1, 'дамасце́нка', 0)
(730, 622, 0, 1, 'авантю́ра', 0)
(731, 622, 0, 2, 'вока́л', 0)
(732, 623, 0, 1, 'де', 0)
(733, 623, 1, 1, 'ат', 0)
(734, 624, 0, 1, 'авантю́ра', 0)
(735, 624, 0, 2, 'еква́тор', 0)
(736, 625, 1, 1, 'Адо́льф', 0)
(737, 626, 0, 1, 'а', 1)
(738, 626, 0, 2, 'же', 1)
(739, 626, 0, 3, 'от', 0)
(740, 627, 0, 1, 'a-', 0)
(741, 627, 0, 2, 'ю́ха́', 0)
(742, 628, 0, 1, 'а', 1)
(743, 628, 0, 2, 'дзусь', 0)
(744, 629, 0, 1, 'а', 1)
(745, 629, 0, 2, 'дивитися', 0)
(746, 630, 0, 1, 'авантю́ра', 0)
(747, 630, 0, 2, 'менший', 0)
(748, 630, 0, 3, 'міні́стр', 0)
(749, 632, 0, 1, 'вовк', 0)
(750, 632, 1, 1, 'Аделаї́да', 0)
(751, 634, 0, 1, 'авантю́ра', 0)
(752, 634, 0, 2, 'дире́ктор', 0)
(753, 635, 1, 1, 'Андріа́н', 0)
(754, 636, 0, 1, 'а', 1)
(755, 637, 0, 1, 'а', 1)
(756, 637, 0, 2, 'дуньдунь', 0)
(757, 638, 0, 1, 'авантю́ра', 0)
(758, 639, 0, 1, 'а', 1)
(759, 639, 0, 2, 'диви́тися', 0)
(760, 639, 1, 1, 'ади́', 0)
(761, 640, 0, 1, 'аеропла́н', 0)
(762, 641, 0, 1, 'аеропла́н', 0)
(763, 642, 0, 1, 'аероста́т', 0)
(764, 643, 0, 1, 'ста́ти', 0)
(765, 644, 0, 1, 'ая́', 0)
(766, 645, 0, 1, 'а', 1)
(767, 645, 0, 2, 'же', 1)
(768, 647, 0, 1, 'авантю́ра', 0)
(769, 647, 0, 2, 'день', 0)
(770, 647, 1, 1, 'ажу́р', 2)
(771, 648, 0, 1, 'ажу́р', 1)
(772, 649, 0, 1, 'я', 0)
(773, 649, 1, 1, 'а́збука', 0)
(774, 653, 0, 1, 'аза́рт', 0)
(775, 654, 1, 1, 'азарни́й', 0)
(776, 655, 0, 1, 'а-', 0)
(777, 655, 0, 2, 'гаси́ти', 0)
(778, 655, 1, 1, 'звисть', 0)
(779, 656, 0, 1, 'аз', 0)
(780, 656, 0, 2, 'бу́ква', 0)
(781, 656, 1, 1, 'абе́тка', 0)
(782, 656, 1, 2, 'алфа́ві́т', 0)
(783, 658, 0, 1, 'а-', 0)
(784, 658, 0, 2, 'жи́ти', 0)
(785, 660, 0, 1, 'де', 1)
(786, 660, 0, 2, 'ось', 0)
(787, 661, 1, 1, 'гав’я́н', 0)
(788, 662, 0, 1, 'а', 1)
(789, 663, 0, 1, 'а', 1)
(790, 663, 0, 2, 'і', 0)
(791, 665, 0, 1, 'а', 1)
(792, 665, 0, 2, 'іно́', 0)
(793, 665, 0, 3, 'іно́се', 0)
(794, 666, 0, 1, 'бе́рег', 0)
(795, 671, 0, 1, 'а-', 0)
(796, 671, 0, 2, 'сиді́ти', 0)
(797, 673, 0, 1, 'а', 1)
(798, 673, 0, 2, 'ка́чка', 0)
(799, 674, 0, 1, 'мо́ре', 0)
(800, 675, 0, 1, 'аквамари́н', 0)
(801, 677, 0, 1, 'аке́ц', 0)
(802, 678, 0, 1, 'кез', 0)
(803, 679, 0, 1, 'кет', 0)
(804, 680, 1, 1, 'а', 1)
(805, 680, 1, 2, 'аке́т', 0)
(806, 680, 1, 3, 'кіт', 0)
(807, 681, 0, 1, 'авантю́ра', 0)
(808, 681, 0, 2, 'клі́мат', 0)
(809, 682, 0, 1, 'а', 1)
(810, 682, 0, 2, 'коза́', 0)
(811, 683, 0, 1, 'авантю́ра', 0)
(812, 683, 0, 2, 'компа́нія', 0)
(813, 683, 0, 3, 'па́сти', 0)
(814, 684, 0, 1, 'авантю́ра', 0)
(815, 684, 0, 2, 'середа́', 0)
(816, 684, 0, 3, 'се́рце', 0)
(817, 685, 0, 1, 'ако́рд', 1)
(818, 686, 0, 1, 'ако́рд', 1)
(819, 687, 0, 1, 'а', 1)
(820, 687, 0, 2, 'ко́ся', 0)
(821, 688, 1, 1, 'аке́т', 0)
(822, 688, 1, 2, 'аке́ц', 0)
(823, 689, 0, 1, 'авантю́ра', 0)
(824, 689, 0, 2, 'креди́т', 0)
(825, 690, 0, 1, 'го́стрий', 0)
(826, 690, 0, 2, 'хі́на', 0)
(827, 691, 0, 1, 'авантю́ра', 0)
(828, 691, 0, 2, 'го́стрий', 0)
(829, 692, 0, 1, 'а́ге́нт', 0)
(830, 693, 0, 1, 'а́ге́нт', 0)
(831, 693, 1, 1, 'акт', 2)
(832, 694, 0, 1, 'а́ге́нт', 0)
(833, 694, 1, 1, 'акт', 1)
(834, 695, 0, 1, 'а́ге́нт', 0)
(835, 695, 0, 2, 'акт', 1)
(836, 697, 0, 1, 'акти́ній', 0)
(837, 698, 0, 1, 'а́ге́нт', 0)
(838, 699, 0, 1, 'акто́р', 0)
(839, 699, 0, 2, 'а́ге́нт', 0)
(840, 700, 0, 1, 'а́ге́нт', 0)
(841, 700, 0, 2, 'акт', 1)
(842, 702, 0, 1, 'Кили́на', 0)
(843, 703, 0, 1, 'авантю́ра', 0)
(844, 704, 0, 1, 'а', 1)
(845, 704, 0, 2, 'ку́р', 0)
(846, 705, 0, 1, 'авантю́ра', 0)
(847, 705, 0, 2, 'курува́ти', 0)
(848, 707, 0, 1, 'куть', 0)
(849, 708, 0, 1, 'куш', 0)
(850, 709, 0, 1, 'авантю́ра', 0)
(851, 709, 0, 2, 'куш', 2)
(852, 709, 0, 3, 'куше́тка', 0)
(853, 710, 0, 1, 'авантю́ра', 0)
(854, 710, 0, 2, 'канта́та', 0)
(855, 711, 1, 1, 'а́кція', 2)
(856, 712, 0, 1, 'а́ге́нт', 0)
(857, 712, 1, 1, 'а́кція', 2)
(858, 713, 0, 1, 'а́ге́нт', 0)
(859, 713, 0, 2, 'а́кція', 1)
(860, 714, 0, 1, 'ава́ч', 0)
(861, 716, 0, 1, 'a', 1)
(862, 716, 0, 2, 'ле', 0)
(863, 716, 1, 1, 'але', 2)
(864, 716, 1, 2, 'аль', 0)
(865, 717, 0, 1, 'а', 1)
(866, 717, 0, 2, 'ле', 0)
(867, 717, 1, 1, 'але', 1)
(868, 718, 0, 1, 'борода́', 0)
(869, 721, 1, 1, 'лю́тня', 0)
(870, 727, 0, 1, 'а́рка', 0)
(871, 727, 1, 1, 'е́ркер', 0)
(872, 729, 0, 1, 'алего́рія', 0)
(873, 731, 0, 1, 'а-', 0)
(874, 732, 0, 1, 'а', 1)
(875, 732, 0, 2, 'ле', 0)
(876, 732, 1, 1, 'а́ле́', 1)
(877, 732, 1, 2, 'але́', 2)
(878, 732, 1, 3, 'ану́', 0)
(879, 734, 0, 1, 'лимо́н', 0)
(880, 735, 0, 1, 'аліме́нти', 0)
(881, 737, 0, 1, 'ла́стовиця', 0)
(882, 737, 0, 2, 'ла́та', 0)
(883, 738, 1, 1, 'галу́н', 1)
(884, 739, 0, 1, 'а́льфа', 0)
(885, 739, 1, 1, 'альфабе́т', 0)
(886, 740, 0, 1, 'хі́мія', 0)
(887, 741, 0, 1, 'а', 1)
(888, 741, 0, 2, 'лю', 0)
(889, 741, 1, 1, 'аля́', 0)
(890, 742, 0, 1, 'алу́н', 0)
(891, 742, 0, 2, 'галу́н', 1)
(892, 744, 0, 1, 'алю́р', 0)
(893, 744, 0, 2, 'але́я', 0)
(894, 745, 0, 1, 'а', 1)
(895, 745, 0, 2, 'ля', 0)
(896, 745, 1, 1, 'алю́', 0)
(897, 746, 1, 1, 'лілія́к', 0)
(898, 747, 0, 1, 'а́рмія', 0)
(899, 748, 0, 1, 'а', 1)
(900, 748, 0, 2, 'ли', 0)
(901, 748, 1, 1, 'а́ле́', 1)
(902, 750, 0, 1, 'ву́лик', 0)
(903, 750, 1, 1, 'ва́лоб', 0)
(904, 751, 0, 1, 'а', 1)
(905, 751, 0, 2, 'бо', 0)
(906, 751, 0, 3, 'ли', 0)
(907, 751, 1, 1, 'або́', 0)
(908, 752, 0, 1, 'ле́бідь', 0)
(909, 757, 0, 1, 'аліме́нти', 0)
(910, 758, 0, 1, 'альт', 0)
(911, 759, 0, 1, 'алти́н', 0)
(912, 759, 0, 2, 'бязь', 0)
(913, 760, 0, 1, 'алего́рія', 0)
(914, 762, 0, 1, 'алфа́ві́т', 0)
(915, 763, 0, 1, 'авантю́ра', 0)
(916, 763, 0, 2, 'лига́ти', 1)
(917, 766, 0, 1, 'оба́', 0)
(918, 768, 0, 1, 'іти́', 0)
(919, 768, 0, 2, 'об', 0)
(920, 771, 0, 1, 'а-', 0)
(921, 771, 0, 2, 'ме́рти', 0)
(922, 774, 0, 1, 'мига́ти', 0)
(923, 775, 0, 1, 'а-', 0)
(924, 775, 0, 2, 'мед', 0)
(925, 776, 0, 1, 'амо́ній', 0)
(926, 778, 0, 1, 'а-', 0)
(927, 778, 0, 2, 'па́м’ять', 0)
(928, 779, 0, 1, 'алюмі́ній', 0)
(929, 779, 0, 2, 'амо́ній', 0)
(930, 780, 1, 1, 'аміа́к', 0)
(931, 781, 0, 1, 'авантю́ра', 0)
(932, 781, 0, 2, 'ме́рти', 0)
(933, 782, 0, 1, 'а-', 0)
(934, 782, 0, 2, 'морфе́ма', 0)
(935, 785, 0, 1, 'а́мфо́ра', 0)
(936, 786, 0, 1, 'амбі́ція', 0)
(937, 787, 0, 1, 'а-', 0)
(938, 787, 0, 2, 'моло́ти', 0)
(939, 788, 0, 1, 'авантю́ра', 0)
(940, 788, 1, 1, 'іму́нний', 0)
(941, 789, 0, 1, 'жи́ти', 0)
(942, 789, 0, 2, 'об', 0)
(943, 789, 0, 3, 'оба́', 0)
(944, 790, 0, 1, 'амфі́бія', 0)
(945, 790, 0, 2, 'бо́рзий', 0)
(946, 791, 0, 1, 'амфі́бія', 0)
(947, 791, 0, 2, 'теа́тр', 0)
(948, 792, 0, 1, 'амфі́бія', 0)
(949, 792, 0, 2, 'бра́ти', 0)
(950, 792, 1, 1, 'а́мпула', 0)
(951, 793, 0, 1, 'жи́ти', 0)
(952, 793, 0, 2, 'на', 1)
(953, 794, 0, 1, 'на', 1)
(954, 795, 0, 1, 'ло́гіка', 0)
(955, 795, 0, 2, 'на', 1)
(956, 796, 0, 1, 'анало́гія', 0)
(957, 799, 0, 1, 'на', 1)
(958, 799, 0, 2, 'пха́ти', 0)
(959, 800, 0, 1, 'а-', 0)
(960, 800, 0, 2, 'архаї́чний', 0)
(961, 801, 0, 1, 'на', 1)
(962, 801, 0, 2, 'ста́ти', 0)
(963, 802, 0, 1, 'на', 1)
(964, 803, 0, 1, 'на', 1)
(965, 803, 0, 2, 'тя́ти', 0)
(966, 803, 1, 1, 'а́том', 0)
(967, 803, 1, 2, 'том', 0)
(968, 804, 0, 1, 'на', 1)
(969, 804, 0, 2, 'діти', 2)
(970, 805, 0, 1, 'на', 1)
(971, 805, 0, 2, 'хро́ніка', 0)
(972, 807, 0, 1, 'лише»', 0)
(973, 810, 0, 1, 'вузьки́й', 0)
(974, 812, 0, 1, 'нутро́', 0)
(975, 816, 1, 1, 'Андріа́н', 0)
(976, 816, 1, 2, 'Андро́ник', 0)
(977, 818, 0, 1, 'Андрі́й', 0)
(978, 819, 0, 1, 'а-', 0)
(979, 819, 0, 2, 'да́ти', 0)
(980, 820, 0, 1, 'авантю́ра', 0)
(981, 820, 0, 2, 'ни́тка', 0)
(982, 821, 0, 1, 'а-', 0)
(983, 822, 0, 1, 'воня́ти', 0)
(984, 823, 0, 1, 'ум', 0)
(985, 823, 0, 2, 'яви́ти', 0)
(986, 824, 0, 1, 'а', 1)
(987, 824, 0, 2, 'ні', 0)
(988, 825, 0, 1, 'ніж', 2)
(989, 826, 1, 1, 'га́нус', 0)
(990, 827, 1, 1, 'я́кір', 0)
(991, 828, 0, 1, 'у', 0)
(992, 829, 0, 1, 'а', 1)
(993, 829, 0, 2, 'но', 0)
(994, 829, 1, 1, 'іно́', 0)
(995, 830, 0, 1, 'а', 1)
(996, 830, 0, 2, 'но', 0)
(997, 830, 1, 1, 'ану́', 0)
(998, 830, 1, 2, 'іно́', 0)
(999, 831, 0, 1, 'а́но́', 1)
(1000, 831, 0, 2, 'лем', 0)
(1001, 832, 0, 1, 'а-', 0)
(1002, 832, 0, 2, 'сам', 0)
(1003, 833, 0, 1, 'а-', 0)
(1004, 833, 0, 2, 'ім’я́', 0)
(1005, 834, 0, 1, 'сам', 0)
(1006, 834, 0, 2, 'у', 0)
(1007, 835, 0, 1, 'а́ге́нт', 0)
(1008, 835, 0, 2, 'анти-', 0)
(1009, 835, 1, 1, 'аго́нія', 0)
(1010, 841, 0, 1, 'анти-', 0)
(1011, 843, 0, 1, 'анти-', 0)
(1012, 843, 0, 2, 'пан-', 0)
(1013, 846, 0, 1, 'анти-', 0)
(1014, 846, 0, 2, 'ві́но', 0)
(1015, 848, 0, 1, 'анти-', 0)
(1016, 848, 0, 2, 'аноні́м', 0)
(1017, 850, 0, 1, 'Андрі́й', 0)
(1018, 850, 0, 2, 'ло́гіка', 0)
(1019, 850, 0, 3, 'сочи́ти', 0)
(1020, 851, 0, 1, 'а', 1)
(1021, 851, 0, 2, 'ну', 0)
(1022, 852, 0, 1, 'авантю́ра', 0)
(1023, 852, 0, 2, 'нуль', 0)
(1024, 853, 0, 1, 'ану́', 0)
(1025, 854, 0, 1, 'цера́та', 0)
(1026, 857, 1, 1, 'анчу́га', 0)
(1027, 858, 0, 1, 'анчо́ус', 0)
(1028, 859, 0, 1, 'вірьо́вка', 0)
(1029, 860, 0, 1, 'авантю́ра', 0)
(1030, 860, 0, 2, 'ви́порток', 0)
(1031, 862, 0, 1, 'а-', 0)
(1032, 862, 0, 2, 'па́фос', 0)
(1033, 863, 0, 1, 'авантю́ра', 0)
(1034, 865, 0, 1, 'авантю́ра', 0)
(1035, 865, 0, 2, 'п’ядь', 0)
(1036, 865, 0, 3, 'пу́дити', 0)
(1037, 866, 0, 1, 'авантю́ра', 0)
(1038, 867, 0, 1, 'авантю́ра', 0)
(1039, 867, 0, 2, 'плести́', 0)
(1040, 868, 0, 1, 'авантю́ра', 0)
(1041, 869, 0, 1, 'авантю́ра', 0)
(1042, 869, 0, 2, 'пло́мба', 0)
(1043, 870, 0, 1, 'абажу́р', 0)
(1044, 870, 1, 1, 'гeo-', 0)
(1045, 871, 0, 1, 'абажу́р', 0)
(1046, 871, 0, 2, 'пла́кати', 0)
(1047, 873, 0, 1, 'абажу́р', 0)
(1048, 873, 0, 2, 'стели́ти', 0)
(1049, 874, 0, 1, 'абажу́р', 0)
(1050, 875, 0, 1, 'авантю́ра', 0)
(1051, 875, 0, 2, 'про́ба', 0)
(1052, 876, 0, 1, 'псик', 0)
(1053, 877, 0, 1, 'абажу́р', 0)
(1054, 877, 0, 2, 'ді́ти', 2)
(1055, 877, 0, 3, 'те́ка', 0)
(1056, 878, 0, 1, 'а', 1)
(1057, 878, 0, 2, 'пу́ля', 0)
(1058, 879, 1, 1, 'озни́ця', 0)
(1059, 880, 1, 1, 'ара́п', 0)
(1060, 881, 0, 1, 'ара́б', 0)
(1061, 882, 1, 1, 'ракі́я', 0)
(1062, 883, 0, 1, 'ара́б', 0)
(1063, 887, 1, 1, 'рума́к', 0)
(1064, 889, 0, 1, 'а-', 0)
(1065, 889, 0, 2, 'арга́т', 0)
(1066, 890, 0, 1, 'аргуме́нт', 0)
(1067, 894, 0, 1, 'авантю́ра', 0)
(1068, 894, 0, 2, 'ста́ти', 0)
(1069, 895, 0, 1, '«споряджати»', 0)
(1070, 896, 0, 1, 'авантю́ра', 0)
(1071, 896, 0, 2, 'гва́рдія', 0)
(1072, 896, 0, 3, 'реа́кція', 0)
(1073, 897, 1, 1, 'арх', 0)
(1074, 898, 1, 1, 'гарма́к', 0)
(1075, 901, 0, 1, 'а', 1)
(1076, 901, 0, 2, 'рист', 0)
(1077, 905, 0, 1, 'аероста́т', 0)
(1078, 906, 0, 1, 'А́рій', 0)
(1079, 909, 1, 1, 'орка́н', 0)
(1080, 910, 0, 1, 'арка́н', 1)
(1081, 911, 0, 1, 'гак', 1)
(1082, 911, 1, 1, 'а́рка', 0)
(1083, 912, 0, 1, 'а́рка', 0)
(1084, 913, 0, 1, 'а́рмія', 0)
(1085, 914, 1, 1, 'а́рмія', 0)
(1086, 914, 1, 2, 'армелик', 0)
(1087, 915, 1, 1, 'а́рмев', 0)
(1088, 916, 1, 1, 'раме́но', 0)
(1089, 916, 1, 2, 'ярмо́', 0)
(1090, 918, 1, 1, 'гарні́вка', 0)
(1091, 921, 1, 1, 'Арсе́н', 0)
(1092, 926, 0, 1, 'аероста́т', 0)
(1093, 933, 0, 1, 'ари́к', 0)
(1094, 936, 0, 1, 'а́нгел', 0)
(1095, 936, 0, 2, 'архаї́чний', 0)
(1096, 937, 0, 1, 'архаї́чний', 0)
(1097, 938, 0, 1, 'архаї́чний', 0)
(1098, 938, 0, 2, 'ло́гіка', 0)
(1099, 939, 0, 1, 'алхі́мія', 0)
(1100, 939, 0, 2, 'архі-', 0)
(1101, 940, 0, 1, 'архі-', 0)
(1102, 941, 0, 1, 'архаї́чний', 0)
(1103, 942, 1, 1, 'архаї́чний', 0)
(1104, 943, 0, 1, 'архі-', 0)
(1105, 944, 0, 1, 'архі-', 0)
(1106, 945, 0, 1, 'архі-', 0)
(1107, 945, 0, 2, 'теса́ти', 0)
(1108, 946, 0, 1, 'ве́рга́ти', 0)
(1109, 949, 0, 1, 'лі́коть', 0)
(1110, 951, 0, 1, 'ря', 0)
(1111, 954, 0, 1, 'а', 1)
(1112, 954, 0, 2, 'са', 0)
(1113, 955, 0, 1, 'авантю́ра', 0)
(1114, 955, 0, 2, 'сам', 0)
(1115, 956, 0, 1, 'саніта́р', 0)
(1116, 957, 0, 1, 'авантю́ра', 0)
(1117, 957, 0, 2, 'сигна́л', 0)
(1118, 958, 0, 1, 'авантю́ра', 0)
(1119, 958, 0, 2, 'сам', 0)
(1120, 958, 0, 3, 'симуля́ція', 0)
(1121, 958, 1, 1, 'асамбле́я', 0)
(1122, 958, 1, 2, 'дисиміля́ція', 0)
(1123, 959, 0, 1, 'авантю́ра', 0)
(1124, 959, 0, 2, 'ста́ти', 0)
(1125, 964, 0, 1, 'авантю́ра', 0)
(1126, 964, 0, 2, 'сорт', 0)
(1127, 965, 0, 1, 'авантю́ра', 0)
(1128, 965, 0, 2, 'соціа́льний', 0)
(1129, 966, 1, 1, 'спа́ржа', 0)
(1130, 967, 0, 1, 'авантю́ра', 0)
(1131, 967, 1, 1, 'па́сти', 0)
(1132, 969, 1, 1, 'я́шма', 0)
(1133, 970, 0, 1, 'авантю́ра', 0)
(1134, 970, 0, 2, 'писк', 0)
(1135, 972, 0, 1, 'а-', 0)
(1136, 973, 0, 1, 'го́стрий', 0)
(1137, 973, 0, 2, 'остю́к', 0)
(1138, 973, 0, 3, 'ость', 0)
(1139, 974, 0, 1, 'а́йстра', 0)
(1140, 974, 0, 2, 'вид', 0)
(1141, 975, 0, 1, 'ане́мона', 0)
(1142, 975, 0, 2, 'ві́яти', 0)
(1143, 976, 0, 1, 'а́йстра', 0)
(1144, 976, 0, 2, 'ло́гіка', 0)
(1145, 976, 1, 1, 'астроно́мія', 0)
(1146, 977, 0, 1, 'а́йстра', 0)
(1147, 978, 0, 1, 'а́йстра', 0)
(1148, 978, 0, 2, 'аргона́вт', 0)
(1149, 978, 1, 1, 'космона́втика', 0)
(1150, 979, 0, 1, 'автоно́мія', 0)
(1151, 979, 0, 2, 'а́йстра', 0)
(1152, 980, 0, 1, 'а-', 0)
(1153, 982, 0, 1, 'а', 1)
(1154, 982, 0, 2, 'сей', 0)
(1155, 982, 0, 3, 'яки́й', 0)
(1156, 983, 0, 1, 'а', 1)
(1157, 983, 1, 1, 'ако́сь', 0)
(1158, 983, 1, 2, 'ко́ся', 0)
(1159, 983, 1, 3, 'ксьо', 0)
(1160, 983, 1, 4, 'сьох-сьох', 0)
(1161, 984, 0, 1, 'а', 1)
(1162, 984, 0, 2, 'той', 0)
(1163, 984, 1, 1, 'ет', 0)
(1164, 985, 0, 1, 'від', 0)
(1165, 985, 0, 2, 'вуй', 0)
(1166, 987, 0, 1, 'а', 1)
(1167, 987, 0, 2, 'тась', 0)
(1168, 987, 1, 1, 'ате́шь', 0)
(1169, 989, 0, 1, 'а-', 0)
(1170, 992, 0, 1, 'склеро́з', 0)
(1171, 993, 0, 1, 'авантю́ра', 0)
(1172, 993, 0, 2, 'тре́тій', 0)
(1173, 993, 0, 3, 'стоя́ти', 0)
(1174, 996, 0, 1, 'Анато́лій', 0)
(1175, 996, 0, 2, 'ато́л', 0)
(1176, 998, 0, 1, 'ві́яти', 0)
(1177, 998, 0, 2, 'сфе́ра', 0)
(1178, 999, 0, 1, 'а', 1)
(1179, 999, 0, 2, 'той', 0)
(1180, 999, 1, 1, 'ая́', 0)
(1181, 1001, 0, 1, 'а-', 0)
(1182, 1001, 0, 2, 'тя́ти', 0)
(1183, 1001, 1, 1, 'анато́мія', 0)
(1184, 1001, 1, 2, 'том', 0)
(1185, 1002, 0, 1, 'ятрі́вка', 0)
(1186, 1003, 0, 1, 'авантю́ра', 0)
(1187, 1003, 0, 2, 'тракт', 0)
(1188, 1004, 0, 1, 'ва́тра', 0)
(1189, 1005, 0, 1, 'авантю́ра', 0)
(1190, 1005, 0, 2, 'трибу́н', 0)
(1191, 1006, 0, 1, 'а-', 0)
(1192, 1006, 0, 2, 'тро́фіка', 0)
(1193, 1007, 0, 1, 'авантю́ра', 0)
(1194, 1007, 0, 2, 'тота́льний', 0)
(1195, 1007, 1, 1, 'атю́', 0)
(1196, 1008, 0, 1, 'тю', 0)
(1197, 1009, 1, 1, 'аго́в', 0)
(1198, 1009, 1, 2, 'агу́', 2)
(1199, 1010, 0, 1, 'яви́ти', 0)
(1200, 1011, 0, 1, 'Áвгуст', 0)
(1201, 1012, 1, 1, 'аге́л', 1)
(1202, 1014, 0, 1, 'а́ге́нт', 0)
(1203, 1014, 0, 2, 'акт', 1)
(1204, 1014, 0, 3, 'біди́ти', 0)
(1205, 1015, 0, 1, 'а-', 0)
(1206, 1016, 0, 1, 'авантю́ра', 0)
(1207, 1016, 0, 2, 'факт', 0)
(1208, 1017, 0, 1, 'авантю́ра', 0)
(1209, 1017, 0, 2, 'факт', 0)
(1210, 1018, 1, 1, 'я́фира', 0)
(1211, 1019, 0, 1, 'авантю́ра', 0)
(1212, 1019, 0, 2, 'фіксува́ти', 0)
(1213, 1020, 0, 1, 'авантю́ра', 0)
(1214, 1020, 0, 2, 'фіксува́ти', 0)
(1215, 1021, 0, 1, 'абажу́р', 0)
(1216, 1021, 0, 2, 'горизо́нт', 0)
(1217, 1022, 0, 1, 'авантю́ра', 0)
(1218, 1022, 0, 2, 'фрикати́вний', 0)
(1219, 1023, 0, 1, 'ана́фема', 0)
(1220, 1024, 1, 1, 'а', 2)
(1221, 1028, 0, 1, 'від', 0)
(1222, 1028, 0, 2, 'се́бе́', 0)
(1223, 1028, 1, 1, 'гаття́', 0)
(1224, 1029, 0, 1, 'го́стрий', 0)
(1225, 1030, 0, 1, 'аци́', 0)
(1226, 1031, 0, 1, 'о́цет', 0)
(1227, 1031, 0, 2, 'етиле́н', 0)
(1228, 1032, 0, 1, 'о́цет', 0)
(1229, 1033, 0, 1, 'ві́дси', 0)
(1230, 1037, 0, 1, 'ац', 0)
(1231, 1038, 0, 1, 'ба́чити', 0)
(1232, 1038, 1, 1, 'ба', 2)
(1233, 1039, 0, 1, 'а', 1)
(1234, 1039, 0, 2, 'і', 0)
(1235, 1039, 0, 3, 'ні', 0)
(1236, 1039, 1, 1, 'чей', 0)
(1237, 1039, 1, 2, 'чи', 0)
(1238, 1040, 0, 1, 'цю', 0)
(1239, 1042, 0, 1, 'а', 1)
(1240, 1042, 0, 2, 'аж', 0)
(1241, 1043, 0, 1, 'а', 1)
(1242, 1043, 0, 2, 'як', 0)
(1243, 1043, 1, 1, 'ато́', 0)
(1244, 1044, 0, 1, 'ай', 1)
(1245, 1045, 1, 1, 'ба', 2)
(1246, 1045, 1, 2, 'бо', 0)
(1247, 1046, 0, 1, 'ба́чити', 0)
(1248, 1046, 1, 1, 'ба', 1)
(1249, 1048, 1, 1, 'ба́ба', 3)
(1250, 1048, 1, 2, 'бабе́ць', 0)
(1251, 1048, 1, 3, 'ба́биці', 0)
(1252, 1048, 1, 4, 'ба́бичка', 0)
(1253, 1048, 1, 5, 'ба́бка', 5)
(1254, 1049, 0, 1, 'ба́ба', 2)
(1255, 1049, 1, 1, 'ба́биці', 0)
(1256, 1049, 1, 2, 'ба́бичка', 0)
(1257, 1049, 1, 3, 'ба́бка', 5)
(1258, 1050, 0, 1, 'ба́бка', 1)
(1259, 1052, 1, 1, 'ба́ба', 1)
(1260, 1052, 1, 2, 'бабо́й', 0)
(1261, 1055, 0, 1, 'бе́дра', 0)
(1262, 1055, 0, 2, 'бе́дрик', 0)
(1263, 1055, 1, 1, 'бабе́ць', 0)
(1264, 1055, 1, 2, 'ба́бка', 4)
(1265, 1056, 0, 1, 'бах', 1)
(1266, 1056, 0, 2, 'бух', 0)
(1267, 1057, 0, 1, 'бац', 0)
(1268, 1058, 0, 1, 'бобівни́к', 0)
(1269, 1058, 1, 1, 'бабко́вий', 0)
(1270, 1058, 1, 2, 'бабчу́к', 0)
(1271, 1060, 0, 1, 'бзді́ти', 0)
(1272, 1061, 1, 1, 'ба́ба', 2)
(1273, 1062, 0, 1, 'ба́ба', 2)
(1274, 1062, 1, 1, 'ба́ба', 3)
(1275, 1062, 1, 2, 'ба́бичка', 0)
(1276, 1062, 1, 3, 'ба́бка', 5)
(1277, 1063, 0, 1, 'ба́ба', 2)
(1278, 1063, 1, 1, 'ба́ба', 3)
(1279, 1063, 1, 2, 'ба́биці', 0)
(1280, 1063, 1, 3, 'ба́бка', 5)
(1281, 1064, 0, 1, 'ба́биці', 0)
(1282, 1066, 0, 1, 'ба́ба', 1)
(1283, 1067, 0, 1, 'ба́ба', 1)
(1284, 1069, 0, 1, 'ба́ба', 1)
(1285, 1069, 1, 1, 'ба́ба', 2)
(1286, 1069, 1, 2, 'ба́бка', 1)

In [23]:
from nltk import FreqDist
import matplotlib.pyplot as plt

In [24]:
# Создание частотного распределения
text = FreqDist(df["text_lower"])
fdist = FreqDist(text)

In [25]:
# Анализ частот
print(fdist.most_common(10))    # 10 самых частых слов

[('дарить сертификат сумма 1000 также 30 кешбэк любимый категория оформление бесплатный дебетовый карта мтс оформить дебетовый карта мтс вечный бесплатный обслуживание ссылка получить гарантировать подарок выгодный условие сертификат номинал 1000 выбор ozon золотой яблоко пятёрочка магнит до 30 кешбэк каждый месяц любимый категория 10 кешбэк продуктовый магазин рынок вечно бесплатный обслуживание платёж перевод до 10 000 кешбэк ежемесячно забрать сертификат течение 30 день момент выпуск карта совершить любой покупка 500 получить сертификат выбор оформить карта', 30), ('забирать сертификат 1000 покупка золотой яблоко ozon wildberries выпуск бесплатный дебетовый карта банк уралсиб нужно сделать оформить бесплатный дебетовый карта банк уралсиб потратить 1000 течение первый 30 день пользование карта получить сертификат 1000 золотой яблоко ozon wildberries кстати карта доступный 30 кешбэк партнёр бонусный рубль трата 12 годовой ежедневный остаток бесплатный снятие наличный поторопиться принять участие пока сертификат разобрать оформить карта', 20), ('банк выйти новый уровень дебетовый карта выпустить аромакарта вкус шоколад клубника кокос сосна мятый банк переставать удивлять выходить лимитировать серия карта аромат выбор карта приятно радовать бонус кэшбэкома вкусно пахнуть преимущество карта помимо крутой аромат кэшбэк рубль 30 покупка партнёр 15 любимый категория обслуживание пополнение перевод бесплатный снятие наличный 500 000 банкомат банк комиссия оплата жку интернет учёба садик карта действовать 14 страна выплата пенсия пособие получить прямо карта выпуск карта бесплатный новый клиент серия аромакарта ограничить выбирать ссылка аромат ваш картхолдер кошелёк сумка быть источать ненавязчивый приятный аромат', 18), ('забирать сертификат 1200 золотой яблоко 1000 кэшбэк покупка альфа банк всё нужно оформить бесплатный карта ссылка совершить любой покупка сумма 1000 первый 60 день получить 1000 кэшбэк карта банк он потратить снять перевести сертификат золотой яблоко 1200 придёт смс указанный номер телефон кроме тот карта каждый месяц доступный 30 кэшбэк категория выбор 100 один категория барабан суперкэшбэк оформление карта ссылка платёж перевод снятие наличный обслуживание бесплатный', 18), ('заливать бак бензин банк менять резина также получать 10 кэшбэк трата автомобиль нужно сделать оформить дебетовый карта drive ссылка промокод vrumvrum совершить любой покупка карта первый 30 день общий сумма 5000 готовый 2000 бонусный рубль прийти карта подарок банк бонус компенсировать бензин автомойка штраф другой автоуслуга также карта получить вечный 10 кэшбэк покупка азс любой автоуслуга автосервис мойка парковка условие крайне выгодный карта drive постоянно возвращать кэшбэк трата автомобиль оформить карта', 14), ('возвращать 2000 балл обычный покупка продукт бесплатный карта кредит европа банк оформить бесплатный карта cc плюс ссылка оплачивать продукт 1000 получать моментальный кешбэк один покупка получить 100 балл весь период акция 2000 балл балл рубль карта максимально выгодный кроме балл повышенный кешбэк билет театр кино другой развлечение магазин золотой яблоко парфюмерия косметика ресторан магазин одежда обувь салон красота экосистема yandex сбер остальной покупка регулярно тратить деньга продукт почему вернуть часть обратно оформить карта ссылка начинать получать балл первый покупка', 14), ('банк открыть доступ бесплатный дебетовый карта авторский дизайн кэшбэкома 30 молодёжь 14 22 год успеть получить карта вечный бесплатный обслуживание переходить ссылка заполнять онлайн заявка выбирать карта понравиться дизайн тираж дизайнерский карта ограничить фишка карта космический кэшбэк рубль самый популярный трата 30 покупка партнёр 20 театр кино супермаркет одежда обувь отличный вариант школьник студент карта который экономить зарабатывать вместо вы доставка карта бесплатный любой удобный время место оформить карта', 14), ('залить бесплатный бак бензин дебетовый карта drive банк управлять ваш расход автомобиль оформить дебетовый карта ссылка получать 10 кэшбэк любой покупка азс управлять ваш расход автомобиль дебетовый карта drive промокод vrumvrum получить 2000 бонус покупка 5000 рубль течение 30 день активация карта потратить бонус бензин другой автоуслуга пользоваться карта получать бонус трата автомобиль покупка азс автосервис запчасть автомойка парковка оплата штраф оформить карта', 14), ('особый дебетовый карта банк банк специально молодёжь кэшбэкома 30 вечный бесплатный обслуживание новый клиент возраст 14 22 год мочь получить стильный карта ссылка выбор вариант дизайнерский карта ограниченный серия успеть получить стильный карта крутой условие бесплатный обслуживание 30 покупка партнёр 20 кэшбэк театр кино кэшбэк супермаркет кэшбэк одежда обувь месяц вернуть 5000 подписка pro 3000 она важный момент кэшбэк рубль карта какой то бонус оформить карта', 10), ('мы', 10)]

In [26]:
print(fdist['банк'])            # Частота конкретного слова

0

In [27]:
print(fdist.hapaxes()[:10])     # Слова, встречающиеся один раз

['новый версия telegram перегревать iphone заваливать пользователь ложный уведомление нажатие который открываться устройство быстрый разряжаться остановить зарядка перегрев баг встречаться стабильный бета версия ios пока временно помогать полный переустановка мессенджер', 'хотеть разрешить ставить учёт машина который числиться угнать база интерпол купить законно соответствовать законопроект внести госдума принять владелец смочь зарегистрировать автомобиль специальный процедура тот поздний оказаться розыск', 'суд обязать девушка выплатить 10 рубль мужчина который облизывать её обувь московский автобус осень прошлое год мужчина лечь нога пассажирка начать трогать её нога согласие облизывать обувь снять всё видео выложить сеть публикация мужчина просить удалить ролик получить отказ обратиться суд который встать сторона посчитать публикация нарушить личный неимущественный право девушка намерить обжаловать решение видео написать другой женщина жаловаться домогательство человек', 'франция стать первый страна евросоюз принять закон запрет соцсеть ребёнок 15 год документ вступать сила сентябрь вход соцсеть пользователь нужно подтверждать возраст платформа быть обязать блокировать доступ несовершеннолетний исключение сделать видео youtube переписка мессенджер', 'завтракать каждый день 28 редкий покупать вещь спонтанно маленький тратить влияние скидка утренний приём пища помогать контролировать эмоция принимать взвесить финансовый решение рассказать исследователь', 'логистический центр wildberries краснодар невинномысск попасть атака беспилотник данные власть компания краснодар пострадать человек невинномысск ещё двое', 'цб скорее весь стать менять ключевой ставка заседание 24 июль большинство аналитик ожидать регулятор сохранить её уровень 14 25 вероятность снижение ставка пока оцениваться низкий', 'мошенник начать разводить пользователь принимать usdt помощь десятичный точка например жертва переводить 455 usdt 455 usdt убеждать вернуть лишний тысяча', 'россиянин предупредить новый схема мошенничество общественный wi fi злоумышленник создавать фейковый точка доступ название похожий сеть аэропорт кафе торговый центр перенаправить пользователь поддельный страница авторизация украсть личный дать', 'заморозить цена продукт предложить госдума речь идти 10 15 социально значимый товар включая хлеб молоко яйцо гречка предлагаться субсидировать производитель зафиксировать стоимость этот продукт весь страна']

In [ ]:
# Визуализация
fdist.plot(30, cumulative=False)

In [ ]:
plt.show()